// Generated by CoffeeScript 1.6.2
(function() {
  var Landing,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Landing = (function() {
    var bar, detail, detailsBtn, handleBar, landing, mainWrap, returnBtn, shareBtn;

    detailsBtn = '';

    returnBtn = '';

    shareBtn = '';

    handleBar = '';

    bar = '';

    mainWrap = '';

    detail = '';

    landing = '';

    function Landing() {
      this.shareHover = __bind(this.shareHover, this);
      this.onReturn = __bind(this.onReturn, this);
      this.onClick = __bind(this.onClick, this);
      this.bindButtons = __bind(this.bindButtons, this);
      this.resizeLanding = __bind(this.resizeLanding, this);
      var _this = this;

      this.detailsBtn = $('.details-btn');
      this.returnBtn = $('.return-btn');
      this.shareBtn = $('.share');
      this.handleBar = $('.handlebar');
      this.bar = $('.bar');
      this.mainWrap = $('#main-wrap');
      this.landing = $('.landing');
      this.detail = $('.detail');
      this.initDetailWaypoint();
      this.initReturnWaypoint();
      this.bindButtons();
      $(window).resize(function(e) {
        return _this.resizeLanding();
      });
      this.resizeLanding();
    }

    Landing.prototype.resizeLanding = function(e) {
      this.landing.css({
        'height': ($(window).height()) + 'px'
      });
      return console.log(this.landing.height());
    };

    Landing.prototype.bindButtons = function() {
      var _this = this;

      this.detailsBtn.bind('click', function(e) {
        return _this.onClick(e, $(e.currentTarget));
      });
      this.returnBtn.bind('click', function(e) {
        return _this.onReturn(e, $(e.currentTarget));
      });
      return this.shareBtn.hover(function(e) {
        return _this.shareHover($(e.currentTarget));
      });
    };

    Landing.prototype.initDetailWaypoint = function() {
      var _this = this;

      return this.handleBar.waypoint(function(direction) {
        _this.bar.toggleClass('collapse');
        $('.wheel-wrap').toggleClass('collapse');
        _this.detailsBtn.toggle();
        return _this.returnBtn.toggleClass('invisible');
      }, {
        offset: '0px'
      });
    };

    Landing.prototype.initReturnWaypoint = function() {
      var _this = this;

      return this.detail.waypoint(function(direction) {
        console.log('FIXIE');
        return _this.returnBtn.toggleClass('collapse');
      }, {
        offset: '80px'
      });
    };

    Landing.prototype.onClick = function(e, el) {
      var href, offsetTop;

      e.preventDefault();
      href = el.attr('href');
      offsetTop = $(href).offset().top - 80;
      return $('body').stop().animate({
        scrollTop: offsetTop
      }, 300);
    };

    Landing.prototype.onReturn = function(e, el) {
      e.preventDefault();
      return el.parent().parent().stop().animate({
        scrollTop: 0
      }, 300);
    };

    Landing.prototype.shareHover = function(el) {
      return $('.share-items').toggleClass('slide-down');
    };

    return Landing;

  })();

  $(document).ready(function() {
    return window.landing = new Landing;
  });

}).call(this);
