// Generated by CoffeeScript 1.6.2
(function() {
  var Sorter,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Sorter = (function() {
    function Sorter() {
      this.bindTextField = __bind(this.bindTextField, this);      this.bindTextField();
    }

    Sorter.prototype.bindTextField = function() {
      return $('#txtfld').bind('textchange', function(e) {
        var currentText;

        console.log($(this).val());
        currentText = $(this).val();
        $('#names li').hide();
        $("#names").find("[data-name*='" + currentText + "']").show();
        return console.log($("#names").find("[data-name*='" + currentText + "']"));
      });
    };

    return Sorter;

  })();

  $(document).ready(function() {
    return window.sorter = new Sorter;
  });

}).call(this);
