// Generated by CoffeeScript 1.6.2
(function() {
  var Landing;

  Landing = (function() {
    function Landing() {}

    $mainWrap({
      constructor: function() {
        var $detail, $landing, $mainWrap;

        console.log('Landing Proto Ready');
        $mainWrap = $('#main-wrap');
        $landing = $('.landing-view');
        return $detail = $('.detail-view');
      },
      listenScroll: function() {
        return $mainWrap.bind('mousewheel', function(event, delta, deltaX, deltaY) {
          return console.console.log(delta, deltaX, deltaY);
        });
      }
    });

    return Landing;

  })();

  $(document).ready(function() {
    var landing;

    return landing = new Landing;
  });

}).call(this);
